//const sender= require('./sender')
//const TrapReceiver= require ('./TrapReceiver')
//const UdpClient=require('./UdpClient')
const UdpServer=require('./UdpServer')
const TrapServer=require('./TrapServer')
const SyslogServer=require('./SyslogServer')